### ISSUE TITLE
Bad call to ECov_* causes R to crash

### ISSUE THREAD

**Issue by tromary** [gstlearn/gstlearn#107]
I encountered this bug when forgetting the parenthesis of ECov_GAUSSIAN() in the following command

model=Model_createFromParam(type = ECov_GAUSSIAN(),range=delta,sill=sig)

This causes R session to abort...

**Comment by fabien-ors** [comment]
This one is a tricky bug... I have to go deeper in the SWIG source code to find the solution...

**Comment by pierre-guillou** [comment]
After some fiddling with R, from what I understand, `ECov_Gaussian` (without parentheses) is a closure while `ECov_Gaussian()` is a value. We can use SWIG typemaps to detect the type of the `Model_createFromParam` argument in the R part of the wrapper. Then we can either
- abort the function with a helpful message if the parentheses are missing, or
- call the closure directly and silence the error.

First solution would be like, in `r/rgstlearn.i`:

```swig
%typemap(scoercein) ECov, ECov &, const ECov, const ECov & %{
  if (typeof($input) == "closure") rlang::abort("Enum should be called with parentheses");
  if (inherits($input, "ExternalReference")) $input = slot($input,"ref");
%}
```

Second solution:

```swig
%typemap(scoercein) ECov, ECov &, const ECov, const ECov & %{
  if (typeof($input) == "closure") $input = $input();
  if (inherits($input, "ExternalReference")) $input = slot($input,"ref");
%}
```
(Excuse my R, I'm still not very proficient).

We need to keep the original handling of the enum value (the `inherits`/`slot` line) since we override the corresponding SWIG typemap.

This might need to be applied on all enums in gstlearn.

**Comment by drenard77810** [comment]
Clearly the second solution seems promising. However, repeating it for all ENUMS, just for the sake of making life easier for R users seems slightly over-demanding, unless a MACRO is used to make this almost systematic.

**Comment by fabien-ors** [comment]
This has been fixed by adding a patch in SWIG which prevents from crashing R when using wrong type of argument. This issue will be solved in the next gstlearn Realease.
