### ISSUE TITLE
change in loadData behavior

### ISSUE THREAD

**Issue by SKNo** [gstlearn/gstlearn#139]
Hi
If I understand correctly  (please correct me if I am wrong)
loadData("folder", "file.txt")
now searches the `file.txt` in the subdirectories `./, doc/data/folder, ../../doc/data/folder and ../../folder` (**doc** is added in 1.1.0)
While nothing major (not an issue) and easy to resolve, this change prevents the previous scripts work just out-of-box. I couldn't find the change in the documentation (didn't search thoroughly).
Thank you

Update : just noticed : there are more changes in v1.1.0 that requires modifications in previous scripts. Will go through my scripts/programs  -- I think we can close this.
(probably I jumped ahead of myself wrt to loadData)

**Comment by fabien-ors** [comment]
Hi

Yes loadData and loadDoc behavior has been changed in v1.1.0.
These two functions lack of documentation, so let me tell you some details here:
1. these functions are useful to locate gstlearn data and markdown files distributed within the gstlearn repository ('doc' folder).
2. they are used as shortcuts in tutorials and courses scripts only for locating requested files locally in the computer (if a  file is not found, it is downloaded from the gstlearn website and located from where it has been downloaded).

Previously, data and markdown files were searched in the current directory only and, if not found (which was usually the case), downloaded in the current directory. This was polluting the current directory and could lead to version issues.
Now (v1.1), data and markdown files are searched in a lot of local folders (you mentioned) that correspond to usual standard search-paths from the gstlearn repository (useful after cloning the repo and launching check* targets for example). If not found, the files are still downloaded from the website in a temporary directory (no more pollution).

So in my opinion, the loadData function should work as before and I would be interested to have a feedback regarding your issue please.

On the other hand, YES, some function prototypes (API) have been modified since v1.0.0 and we don't always ensure retro-compatibility. Impacted functions are listed in the 'CHANGES' file in the repo root. We strongly suggest you to look at our  tutorials that illustrate how to adapt your previous code.

In the future, the API will be more and more stable. Retro-compatibility will be more and more ensure. We tank you for your understanding.

**Comment by SKNo** [comment]
Thank you for your quick and through response 
Now I better understand the design philosophy behind loadData. I used this function in my scripts for local execution.
Thank you for pointing out about ‘CHANGES’, I will check it.
