### ISSUE TITLE
Problème dbStatisticsMono?

### ISSUE THREAD

**Issue by mike-pereira** [gstlearn/gstlearn#204]
Salut,
J'ai un problème avec la fonction dbStatisticsMono. Je ne comprends pas ce qu'elle me retourne. J'ai fait un test où j'ai recalculé à la main les statistiques (moyenne, médiane,...) sur un jeu de données, et la fonction dbStatisticsMono me donne des résultats assez différents. Je mets ci-dessous un script R reproduisant le problème, avec gstlearn v 1.2.3.
++
[dbStatMono.txt](https://github.com/user-attachments/files/15973937/dbStatMono.txt)

Mike

PS: J'ai posté le même issue dans le repo rgeostats par mégarde, dsl

**Comment by drenard77810** [comment]
Je regarde demain. Suis à Sting ce soir
Envoyé depuis mon téléphone Orange
-------- Message original --------
De : mike-pereira
Date : mar. 25 juin 2024 à 17:45
À : gstlearn/gstlearn
Cc : Subscribed
Objet : [gstlearn/gstlearn] Problème dbStatisticsMono? (Issue #204)


Salut,
J'ai un problème avec la fonction dbStatisticsMono. Je ne comprends pas ce qu'elle me retourne. J'ai fait un test où j'ai recalculé à la main les statistiques (moyenne, médiane,...) sur un jeu de données, et la fonction dbStatisticsMono me donne des résultats assez différents. Je mets ci-dessous un script R reproduisant le problème, avec gstlearn v 1.2.3.
++
[dbStatMono.txt](https://github.com/user-attachments/files/15973937/dbStatMono.txt)

Mike

PS: J'ai posté le même issue dans le repo rgeostats par mégarde, dsl

-- 
Reply to this email directly or view it on GitHub:
https://github.com/gstlearn/gstlearn/issues/204

**Comment by drenard77810** [comment]
Hi Mike
You are right... this is a stupid bug.
This statistics method offers a set of various operator possibilities. But all of them were not coded: the "MEDIAN" in particular.
At the end, the resulting Table had a contents which did not match the list of operators provided by the user... and appeared somewhat disorganized. 
This is fixed now and an ultimate check has been added to check that all operators have been coded: otherwise an error is issued and the Table is returned empty.
