### ISSUE TITLE
Cannot fill MatrixSparse

### ISSUE THREAD

**Issue by fabien-ors** [gstlearn/gstlearn#227]
The only way to create and set values into a sparse matrix (MatrixSparse) seems to use Tripets (createFromTriplets or createFromAnyMatrix, etc...). None of the following methods are able to set values into the sparse matrix (example in python) :

```
import gstlearn as gl
m = gl.MatrixSparse(10)
m.fill(2) # Nothing happen
m.fillRandom() # Nothing happen
m.setColumn(2,[1,2,3,4,5,6,7,8,9,10]) # Nothing happen
m.setValue(1,2,3.5) # Nothing happen
# etc...
```

All works correctly if I set flagEigen=0 in the MatrixSparse constructor above

**Comment by drenard77810** [comment]
The method fill() has been corrected in the case of SparseMatrix.
Please note that, in this particular case, the result is a Sparse Matrix (as requested) but where all its elements are set to 'value'. Therefore the resulting matrix, although it obeys to a sparse format, is not sparse at all!!!.

**Comment by drenard77810** [comment]
This bug has been

**Comment by drenard77810** [comment]
The bug has been reopened in order to solve the following extensive solution for writing in Sparse Matrix
Note the final conclusion:
- in CS format, writing is only possible when this takes place at the place of a value already set. Exception: fill() and fillRandom() are valid as they modify the whole contents of the matrix
- in Eigen format, this is valid anytime.
The demonstration is given by the following Python script.

import gstlearn as gl
import gstlearn.plot as gp
import gstlearn.plot3D as gop

opt_eigen = 1
m = gl.MatrixSparse(4,4,opt_eigen)
m.fill(2) 
m.display()

m = gl.MatrixSparse(4,4,opt_eigen)
m.fillRandom()
m.display()

m = gl.MatrixSparse(4,4,opt_eigen)
m.setValue(1,2,3.5)
m.display()

m = gl.MatrixSparse(4,4,opt_eigen)
m.setColumn(2,[1,2,3,4]) 
m.display()

m = gl.MatrixSparse(4,4,opt_eigen)
m.setRow(1,[1,2,3,4]) 
m.display()

m = gl.MatrixSparse(4,4,opt_eigen)
m.setDiagonal([1,2,3,4]) 
m.display()
