### ISSUE TITLE
DOCS: Add "cite" section in README.txt + generate a DOI for better referencing (Zenodo?)

### ISSUE THREAD

**Issue by antoinecollet5** [gstlearn/gstlearn#257]
This code is likely to be cited in many scientific works. It would be a good idea to add a section in the README specifying how to refer to this piece of software. It would also be ideal to create a DOI for the code. I suggest Zenodo, which only takes a few minutes. What's more, you can add a cool Zenodo badge to the README.txt :)

Cheers !
Antoine

**Comment by fabien-ors** [comment]
Thank you for suggestion!

I have already created a DOI for gstlearn repo with Zenodo: https://zenodo.org/records/13343743
Could you tell me if all seems OK for you please? If so, I will update the 3 README.md files!

Another remark: Because the DOI refer to one github 'release', it also designates the corresponding python and R packages delivered for that release.

**Comment by antoinecollet5** [comment]
@fabien-ors thanks for your reply ! Sure the zenodo citation looks good :)
