### ISSUE TITLE
Accessing kriging results (estimation + stdev) through locators?

### ISSUE THREAD

**Issue by nicolas-clausolles** [gstlearn/gstlearn#93]
Hi! A little question about accessing several kriging outputs using locators. I have a code like this:
```python
model = gstl.Model(...)
neigh = gstl.NeighMoving(...)
dbin = gstl.Db(...)
dbout = gstl.Db(...)
gstl.kriging(dbin, dbout, model, neigh, flag_est=True, flag_std=True)
```
After kriging, the `dbout` looks like
```
Variables
---------
Column = 0 - Name = x1 - Locator = x1
Column = 1 - Name = x2 - Locator = x2
Column = 2 - Name = Kriging.z1.estim - Locator = z1
Column = 3 - Name = Kriging.z1.stdev - Locator = NA
```
To get the result of the estimation, I used to use locators: `estim = dbout.getColumnByLocator(gstl.ELoc.Z)`, which I find quite convenient (from a dev point of view).

However, if I want to get also the standard deviation, I currently have to use the variable name: `stdev = dbout.getColumn(" Kriging.z1.stdev")`, which I find less stable (should the naming conventions change over time or whatever).

So I was wondering: Would it make sense to set a Z locator on `Kriging.z1.stdev` too (that is, having `Column = 3 - Name = Kriging.z1.stdev - Locator = z2` above)?

Alternatively, would it be a good idea to have specific locators for standard deviation and variance (like `ELoc.STD` and `ELoc.VAR`)?

**Comment by drenard77810** [comment]
Hi Nicolas
The description that you made is very accurate.
After a Kriging step (or any calculator in general) it has been decided to upgrade one output variable (or several in some case) to a Z-locator. The idea is to prepare the next action in a global workflow: for example, if the next step is a display, the default (if 'name' is not provided) is to consider a possible Z-locatorized variable.

Your proposal (i.e. to set the locator of ALL output variables ... rather than only ONE) makes sense. The only issue would be...
- If the next step is the calculation of variogram, then the multivariate variogram would be triggered ... rather than the variogram of the currently single locatorized variable ... which is ... the kriged result. Everyone knows that this operation does not really make sense anyhow.

So, we still have to measure the other possible consequences... but the idea seems reasonable. However one has to consider the meaning of considering ALL resulting variables of a Kriging step (i.e. a kriged estimate ans a kriged stdv) at the same level (both Z-locatorized). Why?

Another solution is to use the name of the variables (rather than their locator): in that case, you can regroup these two variables by calling them "Kriging*". Would that solution solve your problem?

**Comment by nicolas-clausolles** [comment]
Thanks for the answer Didier. I suspected that the problem would have something to do with the multivariate case...

(I forgot to mention it in this issue, but) I was thinking of having all of them Z-locatorized because I realized that when you only ask for the kriging standard deviation (`(gstl.kriging(dbin, dbout, model, neigh, flag_est=True, flag_std=True)`), then the `Kriging.z1.stdev` gets a `z1` locator on it. But now I understand why, this is consistent with the idea of chained processes you described.

About why considering all variables at the same level:
I have a kind of "interpolator" class that performs "kriging on demand". You parameterize it at initialization, and then you can `__call__` it on any point set you want (internally, it creates an output Db, calls `gstlearn.kriging()` and returns the result as numpy arrays). Depending on the parameterization, it can return the estimation, the standard deviation, or both. So I just want to get "all the kriging-related variables" that have been added to the Db, independently of their nature.

Using "Kriging*" as you propose definitely works, thanks. I was just wondering if there exists another mechanism, to avoid relying on the naming conventions (that can change over time). But for now, I can use it, sure!
